### PR TITLE
Mailing list functions

### PR DESCRIPTION
**Pull request by Ciuffi**
Add firebase functions and a mailchimp signup function.

Add an email signup form using buefy to index.vue

Email success/errors should show up as toasts. 

Still needs styling

Feel free to ask any questions regarding the firebase function

Before we launch the website, the axios post url in Email.vue needs to be changed to a live function.

### CODE REVIEW

**Comment by kozr** [comment]
I'm working on styling

**Comment by kozr** [comment]
I can't make it stick to the left. I give up lol. Please somebody help.

**Comment by Ciuffi** [comment]
@kozr left aligned using a buefy level instead of a container [more info](https://bulma.io/documentation/layout/level/)

**Comment by Ciuffi** [comment]
@kozr is this good to go?

**Pull request merged**
