### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by ianmah**

### CODE REVIEW

**Comment by ianmah** [comment]
I'll take a look at the broken image css. The FAQ section doesn't play well with any elements that come after it. Will look into that too

**Comment by ianmah** [comment]
@Ciuffi Don't see FAQ on the design doc for the nwplus website which is why I ignored those issues. Are we adding a FAQ to this site?

**Comment by Ciuffi** [comment]
@ianmah I'll double check, but we'll need an FAQ section on the other websites for sure, so we might as well get it working

**Comment by ianmah** [comment]
@ciuffi okay, it's fixed anyways

**Comment by Ciuffi** [comment]
The CSS is really broken right now, we should try to fix this up once all the sections have been finished.. for now lets try to use scoped

**Pull request merged**
