### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by Ciuffi**
Add all the basic functionality for pulling sponsors and images from Firebase.

Basic functionality is done, but I could really use some help styling it properly!!

### CODE REVIEW

**Comment by ianmah** [comment]
sponsor
Looks like this to me, not sure why only two are showing up

**Comment by kozr** [comment]
https://stackoverflow.com/questions/41924476/vuejs-v-for-add-bootstrap-row-every-5-items

Styling wise, I think this stackoverflow post may help. If nobody wants to deal with this, I may be able to work on this tomorrow

**Comment by Ciuffi** [comment]
@kozr I'm not sure how responsive that would be, the amount of icons in a row should change depending on your screen size

**Comment by ianmah** [comment]
Would probably be up to design team how to deal with smaller screens. However looking at the spec/figma again there isn't even a sponsors section

**Comment by Ciuffi** [comment]
@ianmah @kozr There isn't a sponsorship section designed, but we're still expected to have one. We're just going to be doing it like we've done it on NwHacks in the past. Check it out to see [how it works](https://2019.nwhacks.io/#/)

**Comment by Ciuffi** [comment]
Theres still some issues with this PR, mostly with CSS, I'll try to fix them after we merge in the footer

**Pull request merged**
