### PR TITLE
Big css cleanup

### PR DESCRIPTION
**Pull request by Ciuffi**
I think the website should no work on mobile! On my phone things are starting to look good:
IMG_3650
IMG_3651
IMG_3652
IMG_3653

It would be really helpful if you guys could try this out on your phone as well. I've added a new command `yarn mobile` which will launch the dev server onto your local network. Make sure your phone is connected to the same network then go to the url shown when you run `yarn mobile`. *Note: This is really helpful for testing since the website will auto refresh on your phone as well!*

### CODE REVIEW

**Comment by luceliu** [comment]
Bless `yarn mobile`. Did some tiny fixes. Is it just me or does anyone else see this on chrome (desktop)? 
image Everything looks fine with devtools, but without it...

**Comment by Ciuffi** [comment]
@luceliu hmm i'm not getting it.. 

@kozr Fixed the image width

**Comment by Ciuffi** [comment]
Added the sun and the people at the top:
image
IMG_5F211EA26D91-1

**Comment by Ciuffi** [comment]
Things left to do:
Extra trees with the squirrel
Blue stripe on why join section

**Pull request merged**
