### PR TITLE
Add navbar

### PR DESCRIPTION
**Pull request by luceliu**
Since there's no light blue 'backsplash' yet, left a purpley background-color so we're able to see the white text. Also no Apercu Pro font-family yet (?) so grabbed HKConcentrate-Medium.

### CODE REVIEW

**Comment by Ciuffi** [comment]
I'm not sure where the contact us link should bring you, but I've added scrollto and links to the other navbar items.

I've also stickied the navbar to the top, I think that its a good idea but it might not be.. Looking forward to hearing your opinion on it.

Some weird css glitches: 
The navbar doesn't seem to have full width at the top, its slightly padded on the left. Not sure how to fix it.

Also the buttons seems to have a white background colour when clicked and don't revert to their original colour.

**Comment by kozr** [comment]
I fixed the padding issue, it was because navbar was in a container in index.vue

**Comment by kozr** [comment]
I think the css could use a little bit of input from the design team now that it's stickied, but otherwise functionalities are perfect.

**Comment by luceliu** [comment]
Thanks y'all 🚀

**Pull request merged**
